/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2017
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 04/06/2016 1:36:29 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package Reika.ReactorCraft.Models;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;
import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;

public class ModelSolarExchanger extends RotaryModelBase
{
	//fields
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape1;
	LODModelPart Shape1a;
	LODModelPart Shape1b;
	LODModelPart Shape1c;
	LODModelPart Shape1d;
	LODModelPart Shape1e;
	LODModelPart Shape1f;
	LODModelPart Shape1g;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape5a;
	LODModelPart Shape5b;
	LODModelPart Shape5c;
	LODModelPart Shape5d;
	LODModelPart Shape5e;
	LODModelPart Shape5f;
	LODModelPart Shape5g;

	public ModelSolarExchanger()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape2 = new LODModelPart(this, 0, 55);
		Shape2.addBox(0F, 0F, 0F, 16, 1, 16);
		Shape2.setRotationPoint(-8F, 23F, -8F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0F);
		Shape2a = new LODModelPart(this, 0, 55);
		Shape2a.addBox(0F, 0F, 0F, 16, 1, 16);
		Shape2a.setRotationPoint(-8F, 8F, -8F);
		Shape2a.setTextureSize(128, 128);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 0F, 0F);
		Shape1 = new LODModelPart(this, 67, 98);
		Shape1.addBox(-0.5F, -6F, 0F, 1, 6, 14);
		Shape1.setRotationPoint(4F, 23.5F, -7F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0.5235988F);
		Shape1a = new LODModelPart(this, 67, 76);
		Shape1a.addBox(-0.5F, 0F, 0F, 1, 6, 14);
		Shape1a.setRotationPoint(4F, 8.5F, -7F);
		Shape1a.setTextureSize(128, 128);
		Shape1a.mirror = true;
		this.setRotation(Shape1a, 0F, 0F, -0.5235988F);
		Shape1b = new LODModelPart(this, 67, 0);
		Shape1b.addBox(0F, 0F, -0.5F, 14, 6, 1);
		Shape1b.setRotationPoint(-7F, 8.5F, 4F);
		Shape1b.setTextureSize(128, 128);
		Shape1b.mirror = true;
		this.setRotation(Shape1b, 0.5235988F, 0F, 0F);
		Shape1c = new LODModelPart(this, 67, 8);
		Shape1c.addBox(0F, -6F, -0.5F, 14, 6, 1);
		Shape1c.setRotationPoint(-7F, 23.5F, 4F);
		Shape1c.setTextureSize(128, 128);
		Shape1c.mirror = true;
		this.setRotation(Shape1c, -0.5235988F, 0F, 0F);
		Shape1d = new LODModelPart(this, 67, 32);
		Shape1d.addBox(-0.5F, 0F, 0F, 1, 6, 14);
		Shape1d.setRotationPoint(-4F, 8.5F, -7F);
		Shape1d.setTextureSize(128, 128);
		Shape1d.mirror = true;
		this.setRotation(Shape1d, 0F, 0F, 0.5235988F);
		Shape1e = new LODModelPart(this, 67, 16);
		Shape1e.addBox(0F, 0F, -0.5F, 14, 6, 1);
		Shape1e.setRotationPoint(-7F, 8.5F, -4F);
		Shape1e.setTextureSize(128, 128);
		Shape1e.mirror = true;
		this.setRotation(Shape1e, -0.5235988F, 0F, 0F);
		Shape1f = new LODModelPart(this, 67, 54);
		Shape1f.addBox(-0.5F, -6F, 0F, 1, 6, 14);
		Shape1f.setRotationPoint(-4F, 23.5F, -7F);
		Shape1f.setTextureSize(128, 128);
		Shape1f.mirror = true;
		this.setRotation(Shape1f, 0F, 0F, -0.5235988F);
		Shape1g = new LODModelPart(this, 67, 24);
		Shape1g.addBox(0F, -6F, -0.5F, 14, 6, 1);
		Shape1g.setRotationPoint(-7F, 23.5F, -4F);
		Shape1g.setTextureSize(128, 128);
		Shape1g.mirror = true;
		this.setRotation(Shape1g, 0.5235988F, 0F, 0F);
		Shape3 = new LODModelPart(this, 20, 30);
		Shape3.addBox(0F, 0F, 0F, 2, 14, 2);
		Shape3.setRotationPoint(5.5F, 9F, 5.5F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 0F);
		Shape3a = new LODModelPart(this, 30, 30);
		Shape3a.addBox(0F, 0F, 0F, 2, 14, 2);
		Shape3a.setRotationPoint(-7.5F, 9F, 5.5F);
		Shape3a.setTextureSize(128, 128);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0F, 0F, 0F);
		Shape3b = new LODModelPart(this, 10, 30);
		Shape3b.addBox(0F, 0F, 0F, 2, 14, 2);
		Shape3b.setRotationPoint(-7.5F, 9F, -7.5F);
		Shape3b.setTextureSize(128, 128);
		Shape3b.mirror = true;
		this.setRotation(Shape3b, 0F, 0F, 0F);
		Shape3c = new LODModelPart(this, 0, 30);
		Shape3c.addBox(0F, 0F, 0F, 2, 14, 2);
		Shape3c.setRotationPoint(5.5F, 9F, -7.5F);
		Shape3c.setTextureSize(128, 128);
		Shape3c.mirror = true;
		this.setRotation(Shape3c, 0F, 0F, 0F);
		Shape4 = new LODModelPart(this, 0, 0);
		Shape4.addBox(0F, 0F, 0F, 14, 5, 14);
		Shape4.setRotationPoint(-7F, 13.5F, -7F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
		Shape5 = new LODModelPart(this, 0, 21);
		Shape5.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape5.setRotationPoint(6.2F, 13.5F, -3F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		this.setRotation(Shape5, 0F, 0F, 0F);
		Shape5a = new LODModelPart(this, 0, 21);
		Shape5a.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape5a.setRotationPoint(-3F, 13.5F, 6.2F);
		Shape5a.setTextureSize(128, 128);
		Shape5a.mirror = true;
		this.setRotation(Shape5a, 0F, 0F, 0F);
		Shape5b = new LODModelPart(this, 0, 21);
		Shape5b.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape5b.setRotationPoint(2F, 13.5F, -7.2F);
		Shape5b.setTextureSize(128, 128);
		Shape5b.mirror = true;
		this.setRotation(Shape5b, 0F, 0F, 0F);
		Shape5c = new LODModelPart(this, 0, 21);
		Shape5c.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape5c.setRotationPoint(2F, 13.5F, 6.2F);
		Shape5c.setTextureSize(128, 128);
		Shape5c.mirror = true;
		this.setRotation(Shape5c, 0F, 0F, 0F);
		Shape5d = new LODModelPart(this, 0, 21);
		Shape5d.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape5d.setRotationPoint(-3F, 13.5F, -7.2F);
		Shape5d.setTextureSize(128, 128);
		Shape5d.mirror = true;
		this.setRotation(Shape5d, 0F, 0F, 0F);
		Shape5e = new LODModelPart(this, 0, 21);
		Shape5e.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape5e.setRotationPoint(-7.2F, 13.5F, -3F);
		Shape5e.setTextureSize(128, 128);
		Shape5e.mirror = true;
		this.setRotation(Shape5e, 0F, 0F, 0F);
		Shape5f = new LODModelPart(this, 0, 21);
		Shape5f.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape5f.setRotationPoint(-7.2F, 13.5F, 2F);
		Shape5f.setTextureSize(128, 128);
		Shape5f.mirror = true;
		this.setRotation(Shape5f, 0F, 0F, 0F);
		Shape5g = new LODModelPart(this, 0, 21);
		Shape5g.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape5g.setRotationPoint(6.2F, 13.5F, 2F);
		Shape5g.setTextureSize(128, 128);
		Shape5g.mirror = true;
		this.setRotation(Shape5g, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList conditions, float phi, float theta)
	{
		Shape2.render(te, f5);
		Shape2a.render(te, f5);
		Shape1.render(te, f5);
		Shape1a.render(te, f5);
		Shape1b.render(te, f5);
		Shape1c.render(te, f5);
		Shape1d.render(te, f5);
		Shape1e.render(te, f5);
		Shape1f.render(te, f5);
		Shape1g.render(te, f5);
		Shape3.render(te, f5);
		Shape3a.render(te, f5);
		Shape3b.render(te, f5);
		Shape3c.render(te, f5);
		Shape4.render(te, f5);
		Shape5.render(te, f5);
		Shape5a.render(te, f5);
		Shape5b.render(te, f5);
		Shape5c.render(te, f5);
		Shape5d.render(te, f5);
		Shape5e.render(te, f5);
		Shape5f.render(te, f5);
		Shape5g.render(te, f5);
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}
