/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2014
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 30/01/2014 7:42:13 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.ReactorCraft.Models;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;

import org.lwjgl.opengl.GL11;

import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;

public class ModelControl extends RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape4;
	LODModelPart Shape4a;
	LODModelPart Shape4b;
	LODModelPart Shape5;
	LODModelPart Shape5a;
	LODModelPart Shape5b;
	LODModelPart Shape5c;
	LODModelPart Shape5d;
	LODModelPart Shape5e;
	LODModelPart Shape5f;
	LODModelPart Shape5g;
	LODModelPart Shape5h;
	LODModelPart Shape5i;
	LODModelPart Shape5j;
	LODModelPart Shape5k;
	LODModelPart Shape6;
	LODModelPart Shape6a;
	LODModelPart Shape6b;
	LODModelPart Shape6c;
	LODModelPart Shape6d;
	LODModelPart Shape6e;
	LODModelPart Shape6f;
	LODModelPart Shape6g;
	LODModelPart Shape6h;
	LODModelPart Shape6u;
	LODModelPart Shape6i;
	LODModelPart Shape6j;
	LODModelPart Shape6k;
	LODModelPart Shape6l;
	LODModelPart Shape6m;
	LODModelPart Shape6n;
	LODModelPart Shape7;
	LODModelPart Shape7a;
	LODModelPart Shape7b;
	LODModelPart Shape7c;
	LODModelPart Shape8;
	LODModelPart Shape9;
	LODModelPart Shape9a;

	public ModelControl()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new LODModelPart(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 16, 1, 16);
		Shape1.setRotationPoint(-8F, 23F, -8F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 38, 19);
		Shape2.addBox(0F, 0F, 0F, 2, 15, 16);
		Shape2.setRotationPoint(6F, 8F, -8F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0F);
		Shape2a = new LODModelPart(this, 0, 19);
		Shape2a.addBox(0F, 0F, 0F, 2, 15, 16);
		Shape2a.setRotationPoint(-8F, 8F, -8F);
		Shape2a.setTextureSize(128, 128);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 0F, 0F);
		Shape3 = new LODModelPart(this, 29, 52);
		Shape3.addBox(0F, 0F, 0F, 12, 15, 2);
		Shape3.setRotationPoint(-6F, 8F, 6F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 0F);
		Shape3a = new LODModelPart(this, 0, 52);
		Shape3a.addBox(0F, 0F, 0F, 12, 15, 2);
		Shape3a.setRotationPoint(-6F, 8F, -8F);
		Shape3a.setTextureSize(128, 128);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0F, 0F, 0F);
		Shape4 = new LODModelPart(this, 0, 71);
		Shape4.addBox(0F, 0F, 0F, 1, 15, 12);
		Shape4.setRotationPoint(3F, 8F, -6F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
		Shape4a = new LODModelPart(this, 0, 71);
		Shape4a.addBox(0F, 0F, 0F, 1, 15, 12);
		Shape4a.setRotationPoint(-4F, 8F, -6F);
		Shape4a.setTextureSize(128, 128);
		Shape4a.mirror = true;
		this.setRotation(Shape4a, 0F, 0F, 0F);
		Shape4b = new LODModelPart(this, 0, 99);
		Shape4b.addBox(0F, 0F, 0F, 2, 15, 12);
		Shape4b.setRotationPoint(-1F, 8F, -6F);
		Shape4b.setTextureSize(128, 128);
		Shape4b.mirror = true;
		this.setRotation(Shape4b, 0F, 0F, 0F);
		Shape5 = new LODModelPart(this, 66, 0);
		Shape5.addBox(0F, 0F, 0F, 2, 15, 1);
		Shape5.setRotationPoint(4F, 8F, -4F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		this.setRotation(Shape5, 0F, 0F, 0F);
		Shape5a = new LODModelPart(this, 74, 0);
		Shape5a.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape5a.setRotationPoint(-6F, 8F, -1F);
		Shape5a.setTextureSize(128, 128);
		Shape5a.mirror = true;
		this.setRotation(Shape5a, 0F, 0F, 0F);
		Shape5b = new LODModelPart(this, 66, 0);
		Shape5b.addBox(0F, 0F, 0F, 2, 15, 1);
		Shape5b.setRotationPoint(-3F, 8F, -4F);
		Shape5b.setTextureSize(128, 128);
		Shape5b.mirror = true;
		this.setRotation(Shape5b, 0F, 0F, 0F);
		Shape5c = new LODModelPart(this, 66, 0);
		Shape5c.addBox(0F, 0F, 0F, 2, 15, 1);
		Shape5c.setRotationPoint(1F, 8F, -4F);
		Shape5c.setTextureSize(128, 128);
		Shape5c.mirror = true;
		this.setRotation(Shape5c, 0F, 0F, 0F);
		Shape5d = new LODModelPart(this, 66, 0);
		Shape5d.addBox(0F, 0F, 0F, 2, 15, 1);
		Shape5d.setRotationPoint(-6F, 8F, -4F);
		Shape5d.setTextureSize(128, 128);
		Shape5d.mirror = true;
		this.setRotation(Shape5d, 0F, 0F, 0F);
		Shape5e = new LODModelPart(this, 66, 0);
		Shape5e.addBox(0F, 0F, 0F, 2, 15, 1);
		Shape5e.setRotationPoint(-6F, 8F, 3F);
		Shape5e.setTextureSize(128, 128);
		Shape5e.mirror = true;
		this.setRotation(Shape5e, 0F, 0F, 0F);
		Shape5f = new LODModelPart(this, 66, 0);
		Shape5f.addBox(0F, 0F, 0F, 2, 15, 1);
		Shape5f.setRotationPoint(-3F, 8F, 3F);
		Shape5f.setTextureSize(128, 128);
		Shape5f.mirror = true;
		this.setRotation(Shape5f, 0F, 0F, 0F);
		Shape5g = new LODModelPart(this, 66, 0);
		Shape5g.addBox(0F, 0F, 0F, 2, 15, 1);
		Shape5g.setRotationPoint(1F, 8F, 3F);
		Shape5g.setTextureSize(128, 128);
		Shape5g.mirror = true;
		this.setRotation(Shape5g, 0F, 0F, 0F);
		Shape5h = new LODModelPart(this, 66, 0);
		Shape5h.addBox(0F, 0F, 0F, 2, 15, 1);
		Shape5h.setRotationPoint(4F, 8F, 3F);
		Shape5h.setTextureSize(128, 128);
		Shape5h.mirror = true;
		this.setRotation(Shape5h, 0F, 0F, 0F);
		Shape5i = new LODModelPart(this, 74, 0);
		Shape5i.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape5i.setRotationPoint(4F, 8F, -1F);
		Shape5i.setTextureSize(128, 128);
		Shape5i.mirror = true;
		this.setRotation(Shape5i, 0F, 0F, 0F);
		Shape5j = new LODModelPart(this, 74, 0);
		Shape5j.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape5j.setRotationPoint(1F, 8F, -1F);
		Shape5j.setTextureSize(128, 128);
		Shape5j.mirror = true;
		this.setRotation(Shape5j, 0F, 0F, 0F);
		Shape5k = new LODModelPart(this, 74, 0);
		Shape5k.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape5k.setRotationPoint(-3F, 8F, -1F);
		Shape5k.setTextureSize(128, 128);
		Shape5k.mirror = true;
		this.setRotation(Shape5k, 0F, 0F, 0F);
		Shape6 = new LODModelPart(this, 84, 0);
		Shape6.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6.setRotationPoint(4F, 6F, -3F);
		Shape6.setTextureSize(128, 128);
		Shape6.mirror = true;
		this.setRotation(Shape6, 0F, 0F, 0F);
		Shape6a = new LODModelPart(this, 84, 0);
		Shape6a.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6a.setRotationPoint(-6F, 6F, -6F);
		Shape6a.setTextureSize(128, 128);
		Shape6a.mirror = true;
		this.setRotation(Shape6a, 0F, 0F, 0F);
		Shape6b = new LODModelPart(this, 84, 0);
		Shape6b.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6b.setRotationPoint(-3F, 6F, -6F);
		Shape6b.setTextureSize(128, 128);
		Shape6b.mirror = true;
		this.setRotation(Shape6b, 0F, 0F, 0F);
		Shape6c = new LODModelPart(this, 84, 0);
		Shape6c.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6c.setRotationPoint(-6F, 6F, 4F);
		Shape6c.setTextureSize(128, 128);
		Shape6c.mirror = true;
		this.setRotation(Shape6c, 0F, 0F, 0F);
		Shape6d = new LODModelPart(this, 84, 0);
		Shape6d.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6d.setRotationPoint(4F, 6F, -6F);
		Shape6d.setTextureSize(128, 128);
		Shape6d.mirror = true;
		this.setRotation(Shape6d, 0F, 0F, 0F);
		Shape6e = new LODModelPart(this, 84, 0);
		Shape6e.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6e.setRotationPoint(1F, 6F, -6F);
		Shape6e.setTextureSize(128, 128);
		Shape6e.mirror = true;
		this.setRotation(Shape6e, 0F, 0F, 0F);
		Shape6f = new LODModelPart(this, 84, 0);
		Shape6f.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6f.setRotationPoint(1F, 6F, -3F);
		Shape6f.setTextureSize(128, 128);
		Shape6f.mirror = true;
		this.setRotation(Shape6f, 0F, 0F, 0F);
		Shape6g = new LODModelPart(this, 84, 0);
		Shape6g.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6g.setRotationPoint(-3F, 6F, -3F);
		Shape6g.setTextureSize(128, 128);
		Shape6g.mirror = true;
		this.setRotation(Shape6g, 0F, 0F, 0F);
		Shape6h = new LODModelPart(this, 84, 0);
		Shape6h.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6h.setRotationPoint(-6F, 6F, -3F);
		Shape6h.setTextureSize(128, 128);
		Shape6h.mirror = true;
		this.setRotation(Shape6h, 0F, 0F, 0F);
		Shape6u = new LODModelPart(this, 84, 0);
		Shape6u.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6u.setRotationPoint(-6F, 6F, 1F);
		Shape6u.setTextureSize(128, 128);
		Shape6u.mirror = true;
		this.setRotation(Shape6u, 0F, 0F, 0F);
		Shape6i = new LODModelPart(this, 84, 0);
		Shape6i.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6i.setRotationPoint(-3F, 6F, 1F);
		Shape6i.setTextureSize(128, 128);
		Shape6i.mirror = true;
		this.setRotation(Shape6i, 0F, 0F, 0F);
		Shape6j = new LODModelPart(this, 84, 0);
		Shape6j.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6j.setRotationPoint(1F, 6F, 1F);
		Shape6j.setTextureSize(128, 128);
		Shape6j.mirror = true;
		this.setRotation(Shape6j, 0F, 0F, 0F);
		Shape6k = new LODModelPart(this, 84, 0);
		Shape6k.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6k.setRotationPoint(4F, 6F, 1F);
		Shape6k.setTextureSize(128, 128);
		Shape6k.mirror = true;
		this.setRotation(Shape6k, 0F, 0F, 0F);
		Shape6l = new LODModelPart(this, 84, 0);
		Shape6l.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6l.setRotationPoint(4F, 6F, 4F);
		Shape6l.setTextureSize(128, 128);
		Shape6l.mirror = true;
		this.setRotation(Shape6l, 0F, 0F, 0F);
		Shape6m = new LODModelPart(this, 84, 0);
		Shape6m.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6m.setRotationPoint(1F, 6F, 4F);
		Shape6m.setTextureSize(128, 128);
		Shape6m.mirror = true;
		this.setRotation(Shape6m, 0F, 0F, 0F);
		Shape6n = new LODModelPart(this, 84, 0);
		Shape6n.addBox(0F, 0F, 0F, 2, 15, 2);
		Shape6n.setRotationPoint(-3F, 6F, 4F);
		Shape6n.setTextureSize(128, 128);
		Shape6n.mirror = true;
		this.setRotation(Shape6n, 0F, 0F, 0F);
		Shape7 = new LODModelPart(this, 94, 0);
		Shape7.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape7.setRotationPoint(4.5F, 5.2F, -5F);
		Shape7.setTextureSize(128, 128);
		Shape7.mirror = true;
		this.setRotation(Shape7, 0F, 0F, 0F);
		Shape7a = new LODModelPart(this, 94, 0);
		Shape7a.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape7a.setRotationPoint(-5.5F, 5.2F, -5F);
		Shape7a.setTextureSize(128, 128);
		Shape7a.mirror = true;
		this.setRotation(Shape7a, 0F, 0F, 0F);
		Shape7b = new LODModelPart(this, 94, 0);
		Shape7b.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape7b.setRotationPoint(1.5F, 5.2F, -5F);
		Shape7b.setTextureSize(128, 128);
		Shape7b.mirror = true;
		this.setRotation(Shape7b, 0F, 0F, 0F);
		Shape7c = new LODModelPart(this, 94, 0);
		Shape7c.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape7c.setRotationPoint(-2.5F, 5.2F, -5F);
		Shape7c.setTextureSize(128, 128);
		Shape7c.mirror = true;
		this.setRotation(Shape7c, 0F, 0F, 0F);
		Shape8 = new LODModelPart(this, 28, 71);
		Shape8.addBox(0F, 0F, 0F, 12, 1, 12);
		Shape8.setRotationPoint(-6F, 4.5F, -6F);
		Shape8.setTextureSize(128, 128);
		Shape8.mirror = true;
		this.setRotation(Shape8, 0F, 0F, 0F);
		Shape9 = new LODModelPart(this, 76, 20);
		Shape9.addBox(-1F, 0F, -1F, 2, 15, 2);
		Shape9.setRotationPoint(0F, 5F, 0F);
		Shape9.setTextureSize(128, 128);
		Shape9.mirror = true;
		this.setRotation(Shape9, 0F, 0.7853982F, 0F);
		Shape9a = new LODModelPart(this, 76, 20);
		Shape9a.addBox(-1F, 0F, -1F, 2, 15, 2);
		Shape9a.setRotationPoint(0F, 5F, 0F);
		Shape9a.setTextureSize(128, 128);
		Shape9a.mirror = true;
		this.setRotation(Shape9a, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li, float phi, float theta)
	{
		Shape1.render(te, f5);
		Shape2.render(te, f5);
		Shape2a.render(te, f5);
		Shape3.render(te, f5);
		Shape3a.render(te, f5);
		Shape4.render(te, f5);
		Shape4a.render(te, f5);
		Shape4b.render(te, f5);
		Shape5.render(te, f5);
		Shape5a.render(te, f5);
		Shape5b.render(te, f5);
		Shape5c.render(te, f5);
		Shape5d.render(te, f5);
		Shape5e.render(te, f5);
		Shape5f.render(te, f5);
		Shape5g.render(te, f5);
		Shape5h.render(te, f5);
		Shape5i.render(te, f5);
		Shape5j.render(te, f5);
		Shape5k.render(te, f5);

		double p = -phi/28D;
		GL11.glTranslated(0, p, 0);
		Shape6.render(te, f5);
		Shape6a.render(te, f5);
		Shape6b.render(te, f5);
		Shape6c.render(te, f5);
		Shape6d.render(te, f5);
		Shape6e.render(te, f5);
		Shape6f.render(te, f5);
		Shape6g.render(te, f5);
		Shape6h.render(te, f5);
		Shape6u.render(te, f5);
		Shape6i.render(te, f5);
		Shape6j.render(te, f5);
		Shape6k.render(te, f5);
		Shape6l.render(te, f5);
		Shape6m.render(te, f5);
		Shape6n.render(te, f5);
		Shape7.render(te, f5);
		Shape7a.render(te, f5);
		Shape7b.render(te, f5);
		Shape7c.render(te, f5);
		Shape8.render(te, f5);
		Shape9.render(te, f5);
		Shape9a.render(te, f5);
		GL11.glTranslated(0, -p, 0);
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}
