/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2013
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 24/09/2013 9:40:19 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.ReactorCraft.Models;

import java.util.List;

import net.minecraft.client.model.ModelRenderer;
import Reika.ReactorCraft.Base.ModelTurbine;

public class ModelTurbine1 extends ModelTurbine
{
	//fields
	ModelRenderer Shape1;
	ModelRenderer Shape1a;
	ModelRenderer Shape2;
	ModelRenderer Shape2a;
	ModelRenderer Shape2b;
	ModelRenderer Shape2c;
	ModelRenderer Shape2d;
	ModelRenderer Shape2e;
	ModelRenderer Shape2f;
	ModelRenderer Shape2g;
	ModelRenderer Shape2h;
	ModelRenderer Shape2i;
	ModelRenderer Shape2j;
	ModelRenderer Shape2k;
	ModelRenderer Shape2l;
	ModelRenderer Shape2m;
	ModelRenderer Shape2n;
	ModelRenderer Shape2o;
	ModelRenderer Shape2p;
	ModelRenderer Shape2q;
	ModelRenderer Shape3;
	ModelRenderer Shape3a;
	ModelRenderer Shape3b;
	ModelRenderer Shape3c;
	ModelRenderer Shape3d;
	ModelRenderer Shape3e;
	ModelRenderer Shape3f;
	ModelRenderer Shape3g;
	ModelRenderer Shape3h;
	ModelRenderer Shape3i;
	ModelRenderer Shape3j;
	ModelRenderer Shape3k;
	ModelRenderer Shape3l;
	ModelRenderer Shape3m;
	ModelRenderer Shape3n;
	ModelRenderer Shape3o;
	ModelRenderer Shape3q;
	ModelRenderer Shape3p;

	public ModelTurbine1()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new ModelRenderer(this, 0, 80);
		Shape1.addBox(-2F, -2F, 0F, 4, 4, 16);
		Shape1.setRotationPoint(0F, 14F, -8F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0.7853982F);
		Shape1a = new ModelRenderer(this, 0, 80);
		Shape1a.addBox(-2F, -2F, 0F, 4, 4, 16);
		Shape1a.setRotationPoint(0F, 14F, -8F);
		Shape1a.setTextureSize(128, 128);
		Shape1a.mirror = true;
		this.setRotation(Shape1a, 0F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 0, 0);
		Shape2.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2.setRotationPoint(0F, 14F, 4F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 2.96706F);
		Shape2a = new ModelRenderer(this, 0, 0);
		Shape2a.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2a.setRotationPoint(0F, 14F, 4F);
		Shape2a.setTextureSize(128, 128);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 0F, 0F);
		Shape2b = new ModelRenderer(this, 0, 0);
		Shape2b.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2b.setRotationPoint(0F, 14F, 4F);
		Shape2b.setTextureSize(128, 128);
		Shape2b.mirror = true;
		this.setRotation(Shape2b, 0F, 0F, 0.1745329F);
		Shape2c = new ModelRenderer(this, 0, 0);
		Shape2c.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2c.setRotationPoint(0F, 14F, 4F);
		Shape2c.setTextureSize(128, 128);
		Shape2c.mirror = true;
		this.setRotation(Shape2c, 0F, 0F, 0.3490659F);
		Shape2d = new ModelRenderer(this, 0, 0);
		Shape2d.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2d.setRotationPoint(0F, 14F, 4F);
		Shape2d.setTextureSize(128, 128);
		Shape2d.mirror = true;
		this.setRotation(Shape2d, 0F, 0F, 0.5235988F);
		Shape2e = new ModelRenderer(this, 0, 0);
		Shape2e.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2e.setRotationPoint(0F, 14F, 4F);
		Shape2e.setTextureSize(128, 128);
		Shape2e.mirror = true;
		this.setRotation(Shape2e, 0F, 0F, 0.6981317F);
		Shape2f = new ModelRenderer(this, 0, 0);
		Shape2f.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2f.setRotationPoint(0F, 14F, 4F);
		Shape2f.setTextureSize(128, 128);
		Shape2f.mirror = true;
		this.setRotation(Shape2f, 0F, 0F, 0.8726646F);
		Shape2g = new ModelRenderer(this, 0, 0);
		Shape2g.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2g.setRotationPoint(0F, 14F, 4F);
		Shape2g.setTextureSize(128, 128);
		Shape2g.mirror = true;
		this.setRotation(Shape2g, 0F, 0F, 1.047198F);
		Shape2h = new ModelRenderer(this, 0, 0);
		Shape2h.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2h.setRotationPoint(0F, 14F, 4F);
		Shape2h.setTextureSize(128, 128);
		Shape2h.mirror = true;
		this.setRotation(Shape2h, 0F, 0F, 1.22173F);
		Shape2i = new ModelRenderer(this, 0, 0);
		Shape2i.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2i.setRotationPoint(0F, 14F, 4F);
		Shape2i.setTextureSize(128, 128);
		Shape2i.mirror = true;
		this.setRotation(Shape2i, 0F, 0F, 1.396263F);
		Shape2j = new ModelRenderer(this, 0, 0);
		Shape2j.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2j.setRotationPoint(0F, 14F, 4F);
		Shape2j.setTextureSize(128, 128);
		Shape2j.mirror = true;
		this.setRotation(Shape2j, 0F, 0F, 1.570796F);
		Shape2k = new ModelRenderer(this, 0, 0);
		Shape2k.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2k.setRotationPoint(0F, 14F, 4F);
		Shape2k.setTextureSize(128, 128);
		Shape2k.mirror = true;
		this.setRotation(Shape2k, 0F, 0F, 1.745329F);
		Shape2l = new ModelRenderer(this, 0, 0);
		Shape2l.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2l.setRotationPoint(0F, 14F, 4F);
		Shape2l.setTextureSize(128, 128);
		Shape2l.mirror = true;
		this.setRotation(Shape2l, 0F, 0F, 1.919862F);
		Shape2m = new ModelRenderer(this, 0, 0);
		Shape2m.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2m.setRotationPoint(0F, 14F, 4F);
		Shape2m.setTextureSize(128, 128);
		Shape2m.mirror = true;
		this.setRotation(Shape2m, 0F, 0F, 2.094395F);
		Shape2n = new ModelRenderer(this, 0, 0);
		Shape2n.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2n.setRotationPoint(0F, 14F, 4F);
		Shape2n.setTextureSize(128, 128);
		Shape2n.mirror = true;
		this.setRotation(Shape2n, 0F, 0F, 2.268928F);
		Shape2o = new ModelRenderer(this, 0, 0);
		Shape2o.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2o.setRotationPoint(0F, 14F, 4F);
		Shape2o.setTextureSize(128, 128);
		Shape2o.mirror = true;
		this.setRotation(Shape2o, 0F, 0F, 2.443461F);
		Shape2p = new ModelRenderer(this, 0, 0);
		Shape2p.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2p.setRotationPoint(0F, 14F, 4F);
		Shape2p.setTextureSize(128, 128);
		Shape2p.mirror = true;
		this.setRotation(Shape2p, 0F, 0F, 2.617994F);
		Shape2q = new ModelRenderer(this, 0, 0);
		Shape2q.addBox(-0.5F, -16F, -1F, 1, 32, 2);
		Shape2q.setRotationPoint(0F, 14F, 4F);
		Shape2q.setTextureSize(128, 128);
		Shape2q.mirror = true;
		this.setRotation(Shape2q, 0F, 0F, 2.792527F);
		Shape3 = new ModelRenderer(this, 11, 0);
		Shape3.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3.setRotationPoint(0F, 14F, -4F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 2.96706F);
		Shape3a = new ModelRenderer(this, 11, 0);
		Shape3a.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3a.setRotationPoint(0F, 14F, -4F);
		Shape3a.setTextureSize(128, 128);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0F, 0F, 0F);
		Shape3b = new ModelRenderer(this, 11, 0);
		Shape3b.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3b.setRotationPoint(0F, 14F, -4F);
		Shape3b.setTextureSize(128, 128);
		Shape3b.mirror = true;
		this.setRotation(Shape3b, 0F, 0F, 0.1745329F);
		Shape3c = new ModelRenderer(this, 11, 0);
		Shape3c.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3c.setRotationPoint(0F, 14F, -4F);
		Shape3c.setTextureSize(128, 128);
		Shape3c.mirror = true;
		this.setRotation(Shape3c, 0F, 0F, 0.3490659F);
		Shape3d = new ModelRenderer(this, 11, 0);
		Shape3d.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3d.setRotationPoint(0F, 14F, -4F);
		Shape3d.setTextureSize(128, 128);
		Shape3d.mirror = true;
		this.setRotation(Shape3d, 0F, 0F, 0.5235988F);
		Shape3e = new ModelRenderer(this, 11, 0);
		Shape3e.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3e.setRotationPoint(0F, 14F, -4F);
		Shape3e.setTextureSize(128, 128);
		Shape3e.mirror = true;
		this.setRotation(Shape3e, 0F, 0F, 0.6981317F);
		Shape3f = new ModelRenderer(this, 11, 0);
		Shape3f.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3f.setRotationPoint(0F, 14F, -4F);
		Shape3f.setTextureSize(128, 128);
		Shape3f.mirror = true;
		this.setRotation(Shape3f, 0F, 0F, 0.8726646F);
		Shape3g = new ModelRenderer(this, 11, 0);
		Shape3g.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3g.setRotationPoint(0F, 14F, -4F);
		Shape3g.setTextureSize(128, 128);
		Shape3g.mirror = true;
		this.setRotation(Shape3g, 0F, 0F, 1.047198F);
		Shape3h = new ModelRenderer(this, 11, 0);
		Shape3h.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3h.setRotationPoint(0F, 14F, -4F);
		Shape3h.setTextureSize(128, 128);
		Shape3h.mirror = true;
		this.setRotation(Shape3h, 0F, 0F, 1.22173F);
		Shape3i = new ModelRenderer(this, 11, 0);
		Shape3i.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3i.setRotationPoint(0F, 14F, -4F);
		Shape3i.setTextureSize(128, 128);
		Shape3i.mirror = true;
		this.setRotation(Shape3i, 0F, 0F, 1.396263F);
		Shape3j = new ModelRenderer(this, 11, 0);
		Shape3j.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3j.setRotationPoint(0F, 14F, -4F);
		Shape3j.setTextureSize(128, 128);
		Shape3j.mirror = true;
		this.setRotation(Shape3j, 0F, 0F, 1.570796F);
		Shape3k = new ModelRenderer(this, 11, 0);
		Shape3k.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3k.setRotationPoint(0F, 14F, -4F);
		Shape3k.setTextureSize(128, 128);
		Shape3k.mirror = true;
		this.setRotation(Shape3k, 0F, 0F, 1.745329F);
		Shape3l = new ModelRenderer(this, 11, 0);
		Shape3l.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3l.setRotationPoint(0F, 14F, -4F);
		Shape3l.setTextureSize(128, 128);
		Shape3l.mirror = true;
		this.setRotation(Shape3l, 0F, 0F, 1.919862F);
		Shape3m = new ModelRenderer(this, 11, 0);
		Shape3m.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3m.setRotationPoint(0F, 14F, -4F);
		Shape3m.setTextureSize(128, 128);
		Shape3m.mirror = true;
		this.setRotation(Shape3m, 0F, 0F, 2.094395F);
		Shape3n = new ModelRenderer(this, 11, 0);
		Shape3n.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3n.setRotationPoint(0F, 14F, -4F);
		Shape3n.setTextureSize(128, 128);
		Shape3n.mirror = true;
		this.setRotation(Shape3n, 0F, 0F, 2.268928F);
		Shape3o = new ModelRenderer(this, 11, 0);
		Shape3o.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3o.setRotationPoint(0F, 14F, -4F);
		Shape3o.setTextureSize(128, 128);
		Shape3o.mirror = true;
		this.setRotation(Shape3o, 0F, 0F, 2.443461F);
		Shape3q = new ModelRenderer(this, 11, 0);
		Shape3q.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3q.setRotationPoint(0F, 14F, -4F);
		Shape3q.setTextureSize(128, 128);
		Shape3q.mirror = true;
		this.setRotation(Shape3q, 0F, 0F, 2.617994F);
		Shape3p = new ModelRenderer(this, 11, 0);
		Shape3p.addBox(-0.5F, -18F, -1F, 1, 36, 2);
		Shape3p.setRotationPoint(0F, 14F, -4F);
		Shape3p.setTextureSize(128, 128);
		Shape3p.mirror = true;
		this.setRotation(Shape3p, 0F, 0F, 2.792527F);
	}

	@Override
	public void renderAll(List li, float phi)
	{
		Shape1.render(f5);
		Shape1a.render(f5);
		Shape2.render(f5);
		Shape2a.render(f5);
		Shape2b.render(f5);
		Shape2c.render(f5);
		Shape2d.render(f5);
		Shape2e.render(f5);
		Shape2f.render(f5);
		Shape2g.render(f5);
		Shape2h.render(f5);
		Shape2i.render(f5);
		Shape2j.render(f5);
		Shape2k.render(f5);
		Shape2l.render(f5);
		Shape2m.render(f5);
		Shape2n.render(f5);
		Shape2o.render(f5);
		Shape2p.render(f5);
		Shape2q.render(f5);
		Shape3.render(f5);
		Shape3a.render(f5);
		Shape3b.render(f5);
		Shape3c.render(f5);
		Shape3d.render(f5);
		Shape3e.render(f5);
		Shape3f.render(f5);
		Shape3g.render(f5);
		Shape3h.render(f5);
		Shape3i.render(f5);
		Shape3j.render(f5);
		Shape3k.render(f5);
		Shape3l.render(f5);
		Shape3m.render(f5);
		Shape3n.render(f5);
		Shape3o.render(f5);
		Shape3q.render(f5);
		Shape3p.render(f5);
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}
